#
# Your Crowdin's credentials
#
api_token_env: CROWDIN_API_TOKEN
project_id_env: CROWDIN_PROJECT_ID
base_path_env: CROWDIN_BASE_PATH


#
# Choose file structure in crowdin
# e.g. true or false
#
preserve_hierarchy: true

#
# Files configuration
#
files: [
 {
  source : "/magnify/locale/django.pot",
  dest: "/backend-magnify.pot",
  translation : "/magnify/locale/%locale_with_underscore%/LC_MESSAGES/django.po",
 },
 {
  source : "/frontend/magnify/i18n/frontend.json",
  dest: "/frontend-magnify.json",
  translation : "/frontend/magnify/i18n/locales/%locale%.json",
 },
 {
  source : "/frontend/demo/i18n/frontend.json",
  dest: "/frontend-demo.json",
  translation : "/frontend/demo/i18n/locales/%locale%.json",
 }
]
