# Generated by Django 4.0.5 on 2022-06-15 13:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_room_meeting_label_jitsiconfig_groupmembers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JitsiConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('has_microphone_by_default', models.BooleanField(default=False)),
                ('has_camera_by_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Jitsi Configuration',
                'verbose_name_plural': 'Jitsi Configurations',
                'db_table': 'magnify_jitsi_configuration',
            },
        ),
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='Membership',
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_meeting',
            new_name='meetings',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_room',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='admin',
            new_name='administrators',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='friday',
            new_name='held_on_friday',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='monday',
            new_name='held_on_monday',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='saturday',
            new_name='held_on_saturday',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='sunday',
            new_name='held_on_sunday',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='thursday',
            new_name='held_on_thursday',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='tuesday',
            new_name='held_on_tuesday',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='wednesday',
            new_name='held_on_wednesday',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='start_Time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='is_admin',
            new_name='is_administrator',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='admin',
            new_name='administrators',
        ),
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='group',
            name='token_id',
        ),
        migrations.AddField(
            model_name='group',
            name='administrators',
            field=models.ManyToManyField(related_name='is_administrator_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='is_member_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Color must be a valid hexa code', regex='^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterModelTable(
            name='membership',
            table='magnify_membership',
        ),
        migrations.DeleteModel(
            name='JitsiConfig',
        ),
        migrations.AddField(
            model_name='jitsiconfiguration',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meeting'),
        ),
        migrations.AddField(
            model_name='jitsiconfiguration',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
    ]
