# Generated by Django 4.0.5 on 2022-06-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_group_room_membership_meeting_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jitsiconfiguration",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="jitsiconfiguration",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.room",
            ),
        ),
    ]
