# Generated by Django 4.0.5 on 2022-06-22 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_group_room_membership_meeting_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars", verbose_name="Avatar"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, spaces, apostrophe and hyphen are allowed",
                        regex="^[a-zA-Z '-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="jitsiconfiguration",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="jitsiconfiguration",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.room",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$",
                        message="Invalid email address",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_-]{3,16}$",
                        message="Username must be between 3 and 16 characters long\n            and contain only letters, numbers, underscores and hyphens.",
                    )
                ],
                verbose_name="username",
            ),
        ),
    ]
