# Generated by Django 4.0.5 on 2022-06-28 09:24

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_jitsiconfiguration_meeting_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.CheckConstraint(
                check=models.Q(("end__gte", django.db.models.expressions.F("start"))),
                name="end_greater_than_start",
            ),
        ),
    ]
