# Generated by Django 4.0.5 on 2022-06-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_meeting_end_greater_than_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ("name",),
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="label",
            options={
                "ordering": ("name",),
                "verbose_name": "Label",
                "verbose_name_plural": "Labels",
            },
        ),
        migrations.AlterModelOptions(
            name="meeting",
            options={
                "ordering": ("-start", "-start_time"),
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ("name",),
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("username",),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.RemoveField(
            model_name="group",
            name="administrators",
        ),
        migrations.RemoveField(
            model_name="label",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="label",
            name="meetings",
        ),
        migrations.RemoveField(
            model_name="label",
            name="rooms",
        ),
        migrations.AddField(
            model_name="group",
            name="labels",
            field=models.ManyToManyField(
                related_name="is_group_label_of", to="core.label"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="labels",
            field=models.ManyToManyField(
                related_name="is_meeting_label_of", to="core.label"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="labels",
            field=models.ManyToManyField(
                related_name="is_room_label_of", to="core.label"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="meetings",
            field=models.ManyToManyField(
                related_name="allowed_groups", to="core.meeting"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="rooms",
            field=models.ManyToManyField(related_name="allowed_groups", to="core.room"),
        ),
    ]
