# Generated by Django 4.0.5 on 2022-06-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_group_options_alter_label_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="meetings",
        ),
        migrations.RemoveField(
            model_name="group",
            name="rooms",
        ),
        migrations.AddField(
            model_name="meeting",
            name="groups",
            field=models.ManyToManyField(
                related_name="related_meetings", to="core.group"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="groups",
            field=models.ManyToManyField(related_name="related_rooms", to="core.group"),
        ),
    ]
