# Generated by Django 4.0.5 on 2022-06-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_group_meetings_remove_group_rooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
