# Generated by Django 4.0.5 on 2022-06-30 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_room_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="is_group_label_of", to="core.label"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="is_member_of",
                through="core.Membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="administrators",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="related_meetings", to="core.group"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="is_meeting_label_of", to="core.label"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="administrators",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="room",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="related_rooms", to="core.group"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="is_room_label_of", to="core.label"
            ),
        ),
    ]
